fail_fast: true
repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: uv run black --check --diff
        language: system
        types: [ python ]
      - id: flake8
        name: flake8
        entry: uv run flake8
        language: system
        types: [ python ]
        require_serial: true
      - id: gitlint
        name: gitlint
        entry: uv run gitlint
        language: system
        args: [--contrib=contrib-title-conventional-commits, --ignore=body-is-missing, --msg-filename]
        stages: [commit-msg]
      - id: mypy
        name: mypy
        entry: uv run mypy src
        language: system
        pass_filenames: false
        types: [ python ]
      - id: pylint
        name: pylint
        entry: uv run pylint -j 0 src
        language: system
        pass_filenames: false
        types: [ python ]
      - id: pyproject-fmt
        name: pyproject-fmt
        entry: uv run pyproject-fmt --check
        files: "^pyproject\\.toml$"
        language: system
